### ISSUE TITLE
Five visible page limit?

### ISSUE THREAD

**Issue by AskYous** [villainoustourist/Blazor.Pagination#2]
This package is great. I don't want to re-invent the wheel. But the 5 page limit is really disappointing. Can we increase/decrease it?

**Comment by villainoustourist** [comment]
VisiblePages is now a parameter, eg.

`            <BlazorPager CurrentPage="@_data.CurrentPage" 
                         PageCount="@_data.PageCount" 
                         OnPageChanged="(async e => { _page = e; await FetchData();})"
                         VisiblePages="10"
                         />`
